node{
  stage('SCM Checkout'){
    git 'https://github.com/kdatta21/testUnderstanding/tree/master/myFirstappUsingMaven'
  }
  stage('Compile-Package'){
    
      def mvnHome =  tool name: 'maven-3', type: 'maven'   
      sh "${mvnHome}/bin/mvn package"
  }
}
